spring:
  application:
    name: food-shop-management
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_foodShop_management
    username: root
    password: MyStrong@Passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
jwt:
  signerKey: EhZgs6o9HQe8iGdmD4QbRFdmVJKrMx31PCei8nnyHaKQCbx3g2kk9flzsaVmKDUr


